document.addEventListener('DOMContentLoaded', function() {
    const bulletPoints = [
        "The innocence of the first inquiry - what am I? - is needed throughout Zen practice",
"The Zen way of calligraphy is to write in the most straightforward, simple way as if you were a beginner, not trying to make something skillful or beautiful, but simply writing with full attention as if you were discovering what you were writing for the first time; then your full nature will be in your writing.",
"A realistic fly often occurs in Mike’s paintings. Suzukiroshi is very fond of the frog, which sits so still it might be asleep, but it is alert enough to notice every insect that comes by. Maybe the fly is waiting for the frog. ",
"Americans have a beginner’s mind, in that they have few preconceptions of Zen, are quite open to it, and confidently believe that it can help their lives. He found they question Zen in a way that gives Zen life.",
"It is difficult because it is hard to keep our mind pure and our practice pure in its fundamental sense",
"All self-centered thoughts limit our vast mind",
"This is also the real secret of the arts: always be a beginner. Be very careful about this point. If you start to practice zazen, you will begin to appreciate your beginner’s mind.",
"Our body and mind are both two and one.",
"After some years we will die. If we just think that this is the end of our life, this will be the wrong understanding. But, on the other hand, if we think that we do not die, this is also wrong. We die, and we do not die. This is the right understanding. ",
"These forms are not a means of obtaining the right state of mind. To take this posture itself is the purpose of our practice. When you have this posture, you have the right state of mind, so there is no need to try to attain some special state. ",
"The most important point is to own our own physical body. If you slump, you will lose yourself. Your mind will be wondering about somewhere else; you will not be in your body.",
"Written teaching is a kind of food for your brain. Of course, it is necessary to take some food for your brain, but it is more important to be yourself by practicing the right way of life. ",
"The state of mind that exists when you sit in the right posture is, itself, enlightenment. ",
"The inner world is limitless, and the out world is also limitless. We say, ‘inner world’ or ‘outer world’ but actually there is just one whole world. ",
"Not-to-do something is doing something. Good and bad are only in your mind. So we should no say, “This is good,” or “This is bad.” Instead, of saying bad, you should say, “not-to-do”!",
"When we lose our balance we die, but at the same time we also develop ourselves, we grow. What we see is changing, losing its balance. The reason everything looks beautiful is because it is out of balance, but its background is always in perfect harmony. ",
"The best way to control people is to encourage them to be mischievous. Then they will be in control in its wider sense. ",
"Zen practice is to open up our small mind. So concentrating is just an aid to help you realize ‘big mind’ or the mind that is everything. If you want to discover the true meaning of Zen in your everyday life, you have to understand the meaning of keeping your mind on your breathing and your body in the right posture of zazen. ",
"Dogen-zenji said, “Time goes from present to past.’",
"People, especially young people, think that freedom is to do just what they want, that in Zen there is no need for rules. But it is absolutely necessary for us to have some rules. But this does not mean always to be under control. As long as you have rules, you have a chance for freedom. To try to obtain freedom without being aware of the rules means nothing. ",
"Do not try to stop your thinking, Let it stop by itself. ",
"A mind with waves in it is not a disturbed mind, but actually an amplified one. Whatever you experience is an expression of big mind. ",
"Because we enjoy all aspect of life an as unfolding of big mind, we do not care of any excessive joy. So we have imperturbable composure, and it is with this imperturbable composure of big mind that we practice [zazen]. ",
"Even though you have some difficulty in your practice, even though you have some waves while you are sitting, those waves themselves will help you. So you should not be bothered by your mind. ",
"Once you understand our innate power to purify ourselves and our surroundings, you can act properly, and you will learn from those around you, and you will become friendly with others. ",
"The posture taken in zazen is not the same for each of us. For some it may be impossible to take the cross-legged posture. But even though you cannot take the right posture, when you arouse your real, way-seeking mind, you can practice Zen in its true sense. Actually it iseasier for those who have difficulties in sitting to arouse the true way-seeking mind than for those that can sit easily. ",
"We say, “A good father is not a good father.” Do you understand? One who thinks he is a good father is not a good father; one who thinks he is a good husband is not a good husband. One who thinks he is one of the worse husbands may be a good one if he is always trying to be a good husband with a single-hearted effort. ",
"In the zazen posture which you acquired by long, hard practice, your mind and body have great power to accept things as they are, whether they are agreeable or disagreeable. ",
"So to find your own way under some restriction is the way of practice.",
"You must be true to your own way until at last you actually come to the point where you see it is necessary to forget all about yourself. Until you come to this point, it is completely mistaken to think that whatever you do is Zen or that is does not matter whether you practice or not. ",
"He never did anything in just a dualistic way; he was ready to die in each moment. In ceremony after ceremony he died, and he renewed himself. This is the spirit of the tea ceremony. This is how we bow. ",
"Bowing helps to eliminate our self-centered ideas. This is not to so easy. It is difficult to get rid of these ideas, and bowing is a very valuable practice. The result is not the point; it is the effort to improve ourselves that is valuable. There is no end to this practice. ",
"Of course, whatever we do is the expression of our true nature, but without this practice it is difficult to realize. It is our human nature to be active and the nature of every existence. As long as we are alive, we are always doing something. But as long as you think, “I am doing  this,” or “I have to do this,” or “I must attain something special,” you are actually not doing anything. ",
"For a mother with children, having children is nothing special. That is zazen. So, if you continue this practice, more and more you will acquire something-nothing special, but nevertheless something.",
"The most important thing is to express your true nature in the simplest, most adequate way and to appreciate it in the smallest existence. ",
"So the purpose of my talk is to express my appreciation, that is all. Our way is not to sit to acquire something; it is to express our true nature. That is our practice. ",
"We should appreciate what we are doing. There is no preparation for something else. ",
"There is no starting point, no goal, nothing to attain. Just to run on the track is our way. This is the nature of our Zen practice. ",
"Just appreciate the sights you see from the train. That is our way. There is no need for the passengers to be curious about the track. Someone willtake care of it; Buddha will take take care of it. ",
"But our spiritual way is not so idealistic. In some sense we should be idealistic; at least we should be interested in making bread which tastes and looks good! Actual practice is repeating over and over again until you find how to become bread. ",
"Concentration on our usual every day routine. If you become too busy and too excited, your mind becomes rough and ragged. This is not food. If possible, try to be always calm and joyful and keep yourself from excitement. Usually we become busier. ",
"Just continue in your calm, ordinary practice and your character will be built up. ",
"You know yourself quite well, and you know how much temperature you need. You know exactly what you need. But if you get too excited, you will forget how much temperature is good for you, and you will lose your way. This is very dangerous. ",
"That pride is extra. What you do is good, but something more is added to it. So, you should get rid of that something which is extra. ",
"When you practice zazen, just practice zazen. If enlightenment comes, it just comes. We should not attach to the attainment. ",
"So try not to see something in particular; try not to achieve anything special. You already have everything in your own pure quality. If you understand this ultimate fact, there is no fear. There may be some difficult, of course, but there is no fear. ",
"But when we do something with a complicated mind, in relation to other things or people, our activity becomes very complex. ",
"The shadow is not actually the thinking itself. Of course it is often necessary to think or prepare before we act. But right thinking does not leave any shadow. Thinking hich leaves traces come out your relative confused mind. ",
"It is necessary to remember what we have done, but we should not become attached to what we have done in some special sense. What we call ‘attachment’ is just these traces of our thought and activity. ",
"So our practice is not a matter of one hour or two hours, or one day or one year. If you practice zazen with your whole body and mind, even for a moment, that is zazen. ",
"Usually when it is so simple we say, ‘Oh I know that! It is quite simple. Everyone knows that.’ But if we do not find its value, it means nothing. ",
"So as long as you have some particular goal in your practice, that practice will not help you completely. It may help as long as you are directed towards that goal, but when you resume your everyday life, it will not work. ",
"But the teaching is not we ourselves; it is some explanation of ourselves. So if you are attached to the teaching or the teacher, that is a big mistake. ",
"When we hear the sound of the pine trees on a windy day, perhaps the wind is just blowing, and the pine tree is just standing in the wind. That is all that they are doing. But the people who listen to the win in the tree will write a poem, or will something unusual. That is, I think, the way everything is. ",
"So if you yourself have true practice, then everything else is practicing our way at the same time. ",
"As long as you can eat when you are eating, you are all right. Do not worry a bit. It means you are you yourself. ",
"When you listen to our teaching with a pure, clear mind, you can accept it as if you were hearing something which you already knew. This is called emptiness, or omnipotent self, or knowing everything. ",
"If you are ready to accept things as they are, you will receive them as old friends, even though you appreciate them with new feeling. ",
"They can appreciate everything. In everything they do, even though it may be very difficult, they will always be able to dissolve their problems by constancy. ",
"We emphasize straightforwardness. You should be true to your feelings, and to your mind, expressing yourself without any reservations. This helps the listener to understand more easily. ",
"When you listen to someone, you should give up all your preconceived ideas and your subjective opinions; you should just listen to him, just observe what his way is. ",
"If you try to adjust yourself in a certain way, you will lose yourself. So without any intentional, fancy way of adjusting yourself, to express yourself freely as you are is the most important thing to make yourself happy, and to make others happy. ",
"The best way is just to practice without saying anything. When we talk about your way, there is apt to be some misunderstanding, because the true way always has at least two sides, the negative and the positive.",
"Although our practice looks very formal, our minds are not formal. ",
"But if your true nature is covered by ideas of economy or efficiency, Dogen’s way makes no sense",
"When you do not realize that you are one with the river, or one with the universe, you have fear. Whether it is separated into drops or not, water is water. Our life and death are the same thing. When we realize this fact we have no fear of death anymore, and we have no actual difficulty in our life. ",
"When the water returns to its original oneness with the river, it no longer has any individual feeling to it; it resumes its own nature, and finds composure. ",
"The most important things in our practice are our physical posture and our way of breathing. We are not so concerned about a deep understanding of Buddhism.",
"Before Buddha attained enlightenment he made all possible efforts for us, and at last he attained a thorough understanding of the various ways. You may think Buddha attained some stage where he was free from karmic life, but it is not so. Many stories were told by Buddha about his experiences after he attained enlightenment. He was not at all different from us. When his country was at war with a powerful neighbor, he told his disciples of his own karma, of how he suffered when we saw his country was going to be conquered by the neighboring king. If he had been someone who had attained an enlightenment in which there was no karm, there would have been no reason for him to suffer so. And even after he attained enlightenment he continued the same effort we are making. But his view of life was not shaky. His view of life was stable, and he watched everyone’s life, including his own life. He watched himself, and he watched others with the same eyes that he watched stones or plants, or anything else. He had a very scientific understanding. That was his way of life after he attained enlightenment. ",
"Without accepting the fact that everything changes we cannot find perfect composure. But unfortunately, although it is true, it is difficult for us to accept it. Because we cannot accept the truth of transiency, we suffer. ",
"We should find perfect existence through imperfect existence. We should find perfection in imperfection. ",
"So until we become strong enough to accept difficulty as pleasure, we have to continue this effort. ",
"We are actually one and the same being. We are the same, and yet different. It is very paradoxical, but actually it is so. ",
"So before you do something, ‘being’ is there, the result is there. Even though you look as if you were sitting quietly, all your activity, past and present, is included; and the result of your sitting is also already there. ",
"Whatever it is, it has some form and color, and that form and color are in perfect harmony with other beings. And there is no trouble. That is what we mean by naturalness.",
"You think, “My friends, all of them, are napping; why shouldn't I? When everyone else is not working, why should I work so hard? When they have a lot of money, why don’t I?” This is not naturalness. Your mind is entangled with some other idea, someone else’s idea, and you are not independent, not yourself, and not natural. ",
"When you do something, you should be completely involved in it. You should devote yourself to it completely. Then you have nothing. ",
"The Buddhist understanding of life includes both existence and non-existence. The bird both exists and does not exist at the same time. ",
"When you understand one thing through and through, you understand everything. When you try to understand everything, you will not understand anything. The best way is to understand yourself, and then you will understand everything. So when you try hard to make your own way, you will help others, and you will be helped by others.",
"But it it is possible to go one mile to the easy, that means it is possible to go one mile to the west. This is freedom. Without this freedom you cannot be concentrated on what you do. You may think you are concentrated on something, but before you obtain this freedom, you will have some uneasiness in what you are doing. Because you are bound by some idea of going east or west, your activity is in dichotomy or duality. ",
"Our mind should be soft and open enough to understand things as they are. When our thinking is soft, it is called imperturbable thinking. This kind of thinking is always stable. It is called mindfulness.",
"Wisdom is not something to learn. Wisdom is something which will come out of your mindfulness. ",
"So it is absolutely necessary for everyone to believe in nothing. But I do not mean voidness. There is something, but that something is something which is always prepared for taking some particular form, and it has some rules, or theory, or truth in its activity. ",
"But that we are attached to some beauty is itself Buddha’s activity. That we dont care for weeds is also Buddha’s activity. We should know that.",
"We should not attach to love alone. We should accept hate. We should accept weeds, despite how we feel about them. If you do not care for them, do not love them; if you love them, then love them. ",
"We do not emphasize anything. All we want to do is to know things just as they are. If we know things as they are, there is nothing to point at; there is no way to grasp anything; there is no thing to grasp. We cannot put emphasis on any point.",
"We we a part of the moon covered by a cloud, or a tree, or a weed, we feel how round the moon is. But when we see the clear moon without anything covering it, we do not feel that roundness the same way we do when we see it through something else. ",
"Even though you do not feel anything when you sit, if you do not have this zazen experience, you cannot find anything; you just find weeds, or trees, or clouds in your daily life; you do not see the moon. …what ever you do life becomes art. ",
"Just this trying is already in itself an expression of our true nature. The meaning lies in the effort itself. We should find out the meaning of our effort before we attain something.",
"Which is more important: to attain enlightenment, or to attain enlightenment before you attain enlightenment; to make a million dollars, or to enjoy your life in your effort, little by little, even though it is impossible to make that million; to be successful, or to find some meaning in your effort to be successful? If you do not know the answer, you will not even be able to practice zazen; if you do know, you will have found the true treasure of life. ",
"To practice zazen with a group i the most important thing for Buddhism - and for us - because this practice is the original way of life. ",
"So just to sit, without any idea of gain, and with the purest intention, to remain as quiet as our original nature - this is our practice.",
"That is all we do, and we are happy in this practice. For us there is no need to understand what Zen is. We are practicing zazen. So for us there is no need to know what Zen is intellectually. This is, I think, very unusual for American society. ",
"So actually, we do not emphasize the sitting posure alone. How to sit is how to act. We study how to act by sitting, and this is the most basic activity for us. That is why we practice zazen in this way. ",
"Religion is everywhere. We have to understand our teaching in this way. We should forget all about some particular teaching; we should not ask which is good or bad. There should not be any particular teaching. Teaching is in each moment, in every existence. That is the true teaching.",
"The best way to find perfect composure is not to retain any idea of things, whatever they may be- to forget all aboutthem and not to leave any trace or shadow of thinking. But if you try to stop your mind or try to go beyond your conscious activity, that will only be another burden. ",
"Your mind is always in intense activity. This is not so good. We should know how to give up our thinking mind, our busy mind. In order to go beyond our thinking faculty, it is necessary to have a firm conviction in the emptiness of your mind. Believing firmly in the perfect rest of our mind, we should resume our pure original state. ",
"When we discuss religion, it should be in the most common and universal way. We should not try to propagate our way by wonderful philosophical thought. ",
"We should always be alert enough to communicate with or without words",
"You are on your way to discovering some appropriate way of life. I think that is our Zen community, our group. ",
"We say ‘big mind’ or ‘small mind’ or ‘Buddha mind’ or ‘Zen mind’ and these words mean something, you know, but something we cannot and should not try to understand in terms of experience. ",
"What we are always talking about is that mind and body, mind and material are always one. But if you listen carelessly it sounds as if we are talking about some attribute of being, or about ‘material’ or ‘spiritual’. That will be a version of it, maybe. ",
"We practice zazen to express our true nature, not to attain enlightenment. ",
"But I do not want to be too serious. If we become too serious, we will lose our way. If we are playing games we will lose your way. Little by little with patience and endurance we must find the way for ourselves, find out how to live with ourselves and each other. In this way we will find out our precepts. If we practice hard, concentrate on zazen, and organize our life so that we can sit well, we will find out what we are doing. But you have to be careful in the rules and way you establish. If it is too strict you will fail, if it is too loose, the rules will not work. Our way should be strict enough to have authority, an authority everyone should obey. The rules should be possible to observe. This is how Zen tradition was built up, decided little by little, created by us in our practice. We cannot force anything. But once the rules have been decided, we should obey them completely until they are changed. It is not a matter of good or bad, convenient or inconvenient. You just do it without question. That way your mind is free. ",
"I feel Americans, especially young Americans, have a great opportunity to find out the true way of life for human beings. You are quite free from material things and you begin Zen practice with a very pure mind, a beginner’s mind. You can understand Buddha’s teaching exactly as he meant it. But we must not be attached to America, to Buddhism, or even to our practice. ",
"The goal of practice is to keep our beginner’s mind. Limitless and ready for anything, this Eastern tabula rasa is not, however, a blank starting point. It is the point. ",
    ];

    document.getElementById('generateButton').addEventListener('click', function() {
        const randomIndex = Math.floor(Math.random() * bulletPoints.length);
        const randomQuote = bulletPoints[randomIndex];
        document.getElementById('quoteDisplay').innerText = randomQuote;
    });

});
